jobs:
- job: linux
  pool: 
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.6'
      Python36:
        python.version: '3.7'
  steps: 
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==0.11.1
        python setup.py build_static build
        python setup.py install
        cibuildwheel --output-dir wheelhouse .

    - task: PublishBuildArtifacts@1
      inputs: 
        pathtoPublish: 'wheelhouse'

- job: macos
  pool: 
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python35:
        python.version: '3.6'
      Python36:
        python.version: '3.7'
  steps: 
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==0.11.1
        python setup.py build_static build
        python setup.py install
        cibuildwheel --output-dir wheelhouse .

    - task: PublishBuildArtifacts@1
      inputs: 
        pathtoPublish: 'wheelhouse'

- job: windows
  pool: 
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python35:
        python.version: '3.6'
      Python36:
        python.version: '3.7'
  steps: 
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==0.11.1
        python setup.py build_static build
        python setup.py install
        cibuildwheel --output-dir wheelhouse .

    - task: PublishBuildArtifacts@1
      inputs: 
        pathtoPublish: 'wheelhouse'
